### ISSUE TITLE
Consider adding option for base_topic_prefix (alias)

### ISSUE THREAD

**Issue by synaptiko** [hardwario/bch-control-tool#2]
I discovered this tool today and it's really great. The only problem I have is that I'm using `base_topic_prefix` in bcg config file: https://github.com/bigclownlabs/bch-gateway/blob/master/turris/etc/init.d/bc-gateway-usb-dongle#L35

Which means that messages for gateway are not delivered.

Would it be possible to add option similar to `gateway` to configure this? So instead of `gateway/{id}/pairing-mode/start` there would be `{prefix}gateway/{id}/pairing-mode/stop`?

**Comment by blavka** [comment]
Thx for report Fix in PR #4
