### ISSUE TITLE
release 1.2 not working

### ISSUE THREAD

**Issue by ajsicek** [hardwario/bch-control-tool#6]
After update to release 1.2.0 bch stopped working.
`bch node list` and `bch gw list` both crash with:
`error: __init__() got an unexpected keyword argument 'use_decimal'`

downgrading back to 1.1.0 solve it for now.

**Comment by blavka** [comment]
Thx for report

**Comment by blavka** [comment]
Fix is in release 1.2.1

**Comment by ajsicek** [comment]
confirmed. works now. Thanks for quick fix
